try:
    go_do_something()
except Exception as e:
    print('Computer says no. Reason :', e)
